spring.application.name=Qore
server.servlet.context-path=/api/v1


spring.datasource.url=jdbc:postgresql://localhost:5432/qore
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=UnaClaveSuperSeguraDeAlMenos256Bits1234567890
jwt.expiration=3600000

#mercadopago:

mp.access-token:TEST-5303741500255811-090415-21524c05d647032ac8a67b05ebe7f576-1224195682
mp.public-key:TEST-c94caf16-1799-42c1-a755-0aa0894e64ad
mp.notification-url:https://a76c5f076463.ngrok-free.app/api/v1/payments-webhook/webhook
mp.currency: PEN


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jeisson12aaron@gmail.com
spring.mail.password=axtt xqtk qjbg nnmx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true