spring.application.name=Qore
server.servlet.context-path=/api/v1


spring.datasource.url=jdbc:postgresql://localhost:5432/qore
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=UnaClaveSuperSeguraDeAlMenos256Bits1234567890
jwt.expiration=3600000

#mercadopago:
#    access-token: ${MP_ACCESS_TOKEN_TEST}
#    public-key: ${MP_PUBLIC_KEY_TEST}
#    notification-url: https://TU_DOMINIO.ngrok.io/payments/webhook
#    currency: PEN

mp.access-token:TEST-5303741500255811-090415-2
mp.public-key:TEST-c94ca
mp.notification-url: https://c2abbf69d55b.ngrok-free.app/api/v1/payments-webhook/webhook
mp.currency: PEN
