spring.application.name=Qore
server.servlet.context-path=/api/v1


spring.datasource.url=jdbc:postgresql://localhost:5432/qore
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=UnaClaveSuperSeguraDeAlMenos256Bits1234567890
jwt.expiration=3600000

#mercadopago:

mp.access-token:
mp.public-key:
mp.notification-url: https://a429b29a82f6.ngrok-free.app/api/v1/payments-webhook/webhook
mp.currency: PEN


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jeisson12aaron@gmail.com
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true